### ISSUE TITLE
Function export does not work

### ISSUE THREAD

**Issue by FinnT730** [JannisX11/animator#2]
If I want to export my animation in 1.12, it does not generate the function files.
I don't know if I do something wrong, but it does also not work for 1.14.

How to reproduce:
1. Make a simple animation
2. save it
3. Export it do the function files
4. Done

**Comment by JannisX11** [comment]
For some reason you need to create a folder called "scenes" inside the functions folder you select for it to work.

**Comment by FinnT730** [comment]
Ahhh, I didn't know that, thanks!
It works now!

**Comment by JannisX11** [comment]
Fixed in 1.1.1.
